Review 1 src
xdx505/PlayersOnline pull request #2
Opened 2021-01-07 13:20 UTC by xdx505

2021-01-07 15:59 UTC, LionZXY requested changes

2021-01-07 15:59 UTC, LionZXY commented on README.txt
> +some small patches to the vanilla MCP source code, giving you and it access
Может сделать нормальный README.md с описанием для чего этот мод и прочее?

2021-01-07 15:59 UTC, LionZXY commented on build.gradle
> +group = 'com.yourname.modid' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
Замени название пакета на свое

2021-01-07 15:59 UTC, LionZXY commented on build.gradle
> +archivesBaseName = 'modid'
И название мода

2021-01-07 15:59 UTC, LionZXY commented on build.gradle
> +            "Specification-Title": "examplemod",
Тут тоже все на свое замени)

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/PlayersOnline.java
> +@Mod("playersonline")
Я бы вынес modid в константу

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +            e.printStackTrace();
Лучше будет прокинуть logger объект в init метод и логировать именно туда ошибки и прочее

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +            server.createContext("/test/", this);
Порт, путь и хост имеет смысл вынести в конфиг. И еще - что за параметр в конце?

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +        if (is==null) {
Выглядит как будто тут не хватает пробелов. Ты делал автоформатирование на этот файл?

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +        final Gson gson = new Gson();
Лучше создать `Gson` в самом классе один раз, а не создавать на каждый запрос

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +        for (ServerPlayerEntity player: is.getPlayerList().getPlayers()) {
Тут может быть ошибка, если во время перечисления кто-то выйдет или войдет из/в сервера. Потому-что перечисляешь игроков ты в одном потоке, а изменяться список может в другом. Решений много. Первое костыльно, но рабочее, это использовать for с индексом (`for (int i =0; i < players.size(); i++)`), второе - это использовать `Collections.copy()`.
Или просто передать в `ArrayList<>()` список как аргумент конструктора

2021-01-07 15:59 UTC, LionZXY commented on src/main/java/com/xdx505/playersonline/Server.java
> +        os.close();
Любые потоки нужно оборачивать `try finally` или `try with resources`

2021-01-07 15:59 UTC, LionZXY commented on src/main/resources/META-INF/mods.toml
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu t
Ну ты вставь тут свое описание, чего ты)

2021-01-07 15:59 UTC, LionZXY commented on src/main/resources/META-INF/mods.toml
> +side="BOTH"
А зачем твой мод на клиенте?

2021-01-07 15:59 UTC, LionZXY commented on src/main/resources/META-INF/mods.toml
> +side="BOTH"
Аналогично

2021-01-07 15:59 UTC, LionZXY commented on src/main/resources/pack.mcmeta
> +        "description": "examplemod resources",
Поменяй на свой модайди

2021-01-08 08:42 UTC, closed without merging

2021-01-08 11:48 UTC, xdx505 commented on src/main/java/com/xdx505/playersonline/Server.java
> +        if (is==null) {
Нет, теперь буду знать. Ctrl + Alt + L

2021-01-08 11:50 UTC, xdx505 commented on src/main/java/com/xdx505/playersonline/Server.java
> +            server.createContext("/test/", this);
Указывает какой объект класса HttpHandler или его наследника мы используем в методе

2021-01-08 12:04 UTC, xdx505 commented on src/main/java/com/xdx505/playersonline/Server.java
> +        for (ServerPlayerEntity player: is.getPlayerList().getPlayers()) {
Занёс `is.getPlayerList().getPlayers()` в отдельную переменную перед циклом:
```
final List<ServerPlayerEntity> list = is.getPlayerList().getPlayers();
final List<String> playersList = new ArrayList<>();

for (ServerPlayerEntity player : list) {
      playersList.add(player.getName().getString());
}
```